name: CI
on:
  push:
    branches:
      - master
    # tags:
    #   - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 打印文件夹
        run: ls -a
