name: CI
on:
  push:
    branches:
      - master
    # tags:
    #   - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - name: 打印文件夹
        run: ls -a
      - name: 打印cargo
        run: cargo -v
      - name: 打印rustup
        run: rustup show
