name: CI
on:
  push:
    branches:
      - master
    # tags:
    #   - v*
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      app_name: pass-json
    strategy:
      matrix:
        build: [linux, windows, macos]
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            archive-name: ${{ env.app_name }}-linux.tar.gz
          - build: windows
            os: windows-latest
            target: x86_64-apple-darwin
            archive-name: ${{ env.app_name }}-macos.tar.gz
          - build: macos
            os: macos-latest
            target: x86_64-pc-windows-msvc
            archive-name: ${{ env.app_name }}-windows.7z
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - name: Build Binary
        run: cargo build --release --target ${{ matrix.target }}
      - name: Publish
        run: cargo publish --token ${{ secrets.CRATE_TOKEN }}
      
